-- Migration 013: Expand Nha Trang street list
-- Adds ~70 additional streets not in seed_reference_data.sql
-- Idempotent via ON CONFLICT DO NOTHING

INSERT INTO nha_trang_streets (name, name_ascii) VALUES
    -- Central / commercial area
    ('Nguyễn Huệ',              'Nguyen Hue'),
    ('Đinh Tiên Hoàng',         'Dinh Tien Hoang'),
    ('Trần Nhân Tông',          'Tran Nhan Tong'),
    ('Trần Quốc Toản',          'Tran Quoc Toan'),
    ('Hồng Bàng',               'Hong Bang'),
    ('Ngô Quyền',               'Ngo Quyen'),
    ('Đặng Tất',                'Dang Tat'),
    ('Nguyễn Văn Cừ',           'Nguyen Van Cu'),
    ('Bạch Đằng',               'Bach Dang'),
    ('Cô Bắc',                  'Co Bac'),
    ('Thi Sách',                'Thi Sach'),
    ('Chu Văn An',              'Chu Van An'),
    ('Phạm Hùng',               'Pham Hung'),
    ('Đặng Văn Lý',             'Dang Van Ly'),
    -- Northwest / Phương Sài / Ngọc Hiệp area
    ('Điện Biên Phủ',           'Dien Bien Phu'),
    ('Lê Văn Hưu',              'Le Van Huu'),
    ('Đinh Công Tráng',         'Dinh Cong Trang'),
    ('Phan Đình Phùng',         'Phan Dinh Phung'),
    ('Nam Quốc Cang',           'Nam Quoc Cang'),
    ('Phạm Hồng Thái',          'Pham Hong Thai'),
    ('Duy Tân',                  'Duy Tan'),
    ('Lê Duẩn',                 'Le Duan'),
    ('Nguyễn Văn Trỗi',         'Nguyen Van Troi'),
    ('Trương Định',             'Truong Dinh'),
    ('Trần Bình Trọng',         'Tran Binh Trong'),
    ('Phan Tất Thành',          'Phan Tat Thanh'),
    ('Trần Nguyên Hãn',         'Tran Nguyen Han'),
    ('Nguyễn Bá Học',           'Nguyen Ba Hoc'),
    -- Lộc Thọ / Phước Hải / Vĩnh Nguyên area
    ('Đinh Bộ Lĩnh',            'Dinh Bo Linh'),
    ('Vạn Kiếp',                'Van Kiep'),
    ('Hải Phòng',               'Hai Phong'),
    ('Kinh Dương Vương',        'Kinh Duong Vuong'),
    ('Thái Thị Bôi',            'Thai Thi Boi'),
    ('Tuệ Tĩnh',                'Tue Tinh'),
    ('Lạc Thiên',               'Lac Thien'),
    ('Nguyễn Bỉnh Khiêm',       'Nguyen Binh Khiem'),
    -- Vĩnh Hải / Vĩnh Trường area
    ('Võ Thị Nhờ',              'Vo Thi Nho'),
    ('Phạm Văn Nghị',           'Pham Van Nghi'),
    ('Ngô Đức Kế',              'Ngo Duc Ke'),
    ('Thống Nhất',               'Thong Nhat'),
    ('Nguyễn Thái Học',         'Nguyen Thai Hoc'),
    ('Trần Thái Tông',          'Tran Thai Tong'),
    ('Tô Hiệu',                 'To Hieu'),
    -- Phước Long / outlying
    ('Đường 2/4',               'Duong 2/4'),
    ('Nguyễn Chí Thanh',        'Nguyen Chi Thanh'),
    ('Nguyễn Thế Lộc',          'Nguyen The Loc'),
    ('Phạm Văn Đồng',          'Pham Van Dong'),
    ('Cao Bá Quát',             'Cao Ba Quat'),
    ('Mai Xuân Thưởng',         'Mai Xuan Thuong'),
    -- Tháp Bà / coastal north
    ('Hà Ra',                   'Ha Ra'),
    ('Lê Hồng Phong',           'Le Hong Phong'),
    ('Ngô Sĩ Liên',            'Ngo Si Lien'),
    -- Võ Thị Sáu area / south
    ('Cách Mạng Tháng Tám',    'Cach Mang Thang Tam'),
    ('Pasteur',                  'Pasteur'),
    ('Nam Kỳ Khởi Nghĩa',      'Nam Ky Khoi Nghia'),
    ('Nguyễn Công Trứ',         'Nguyen Cong Tru'),
    ('Phan Bội Châu',           'Phan Boi Chau'),
    -- Additional streets found in listings
    ('Trần Văn Ơn',             'Tran Van On'),
    ('Nguyễn Du',               'Nguyen Du'),
    ('Nguyễn Đình Chiểu',      'Nguyen Dinh Chieu'),
    ('Nguyễn Trung Trực',       'Nguyen Trung Truc'),
    ('Vũ Trọng Phụng',         'Vu Trong Phung'),
    ('Lê Lai',                  'Le Lai'),
    ('Hoàng Diệu',              'Hoang Dieu'),
    ('Minh Khai',               'Minh Khai'),
    ('Tản Viên',                'Tan Vien'),
    ('Nguyễn Văn Linh',        'Nguyen Van Linh'),
    ('Đào Duy Từ',              'Dao Duy Tu'),
    ('Hồ Xuân Hương',           'Ho Xuan Huong'),
    ('Lưu Trọng Lư',           'Luu Trong Lu')
ON CONFLICT DO NOTHING;
